version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/FashionFitsMe
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Satn200@
      SPRING_REDIS_HOST: redis-service
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-service
      - redis-service
    networks:
      - virtualfiton-network

  mysql-service:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Satn200@
      MYSQL_DATABASE: FashionFitsMe
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - virtualfiton-network

  redis-service:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - virtualfiton-network


  bodymeasurements-service:
    image: bodymeasurementsapp
    ports:
      - "6000:6000"

networks:
  virtualfiton-network:
    driver: bridge

volumes:
  mysql_data: