version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/FashionFitsMe
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Satn200@
      SPRING_REDIS_HOST: redis-service
      SPRING_REDIS_PORT: 6379

    depends_on:
      - redis-service

  redis-service:
    image: redis
    ports:
      - "6379:6379"
