version: '3.8'

services:
  spring-app:
    image: tnehara831/fashionfitsme-backend:latest
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/FashionFitsMe
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: OshanD991260099V
      SPRING_REDIS_HOST: redis-service
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql-service
      - redis-service

  mysql-service:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Satn200@
      MYSQL_DATABASE: FashionFitsMe
    volumes:
      - mysql_data:/var/lib/mysql

  redis-service:
    image: redis:latest
    ports:
      - "6379:6379"

  bodymeasurements-service:
    image: bodymeasurementsapp
    ports:
      - "6000:6000"

networks:
  virtualfiton-network:
    driver: bridge